spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  jpa:
    ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
app:
  caches:
    - book
    - bookByNameAndAuthor
    - books