spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  redis:
    host: localhost
    port: 6379
  jpa:
    ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
app:
  caches:
    - book
    - bookByNameAndAuthor
    - books